"""
Core services for the Financial Reasoning Engine.

This module contains the orchestration logic for generating evidence-based
financial insights by reasoning over the context provided by the RAG engine.
"""

from __future__ import annotations

import asyncio
import logging

from backend.schemas.rag_schemas import RAGContext
from backend.schemas.reasoning_schemas import Finding, ReasoningQuery, ReasoningResult
from backend.services.rag_service import RAGEngineService
from backend.services.reasoning.base import ReasoningStrategy


class ReasoningEngineService:
    """
    Orchestrates multiple reasoning strategies to analyze RAG context.

    This service runs various strategies in parallel, each designed to extract
    a different type of insight (e.g., historical parallels, market impact).
    It then aggregates the findings from all strategies.
    """

    def __init__(self, strategies: list[ReasoningStrategy], logger: logging.Logger | None = None):
        """Initialize with a list of reasoning strategies."""
        self._strategies = strategies
        self._logger = logger or logging.getLogger(__name__)

    async def reason(self, context: RAGContext) -> list[Finding]:
        """
        Execute all registered reasoning strategies on the given RAG context.

        Args:
            context: The assembled context from the RAG engine.

        Returns:
            A list of all findings generated by the strategies.
        """
        self._logger.info("Executing %d reasoning strategies.", len(self._strategies))
        tasks = [strategy.analyze(context) for strategy in self._strategies]
        results = await asyncio.gather(*tasks, return_exceptions=True)

        all_findings: list[Finding] = []
        for i, result in enumerate(results):
            if isinstance(result, Exception):
                self._logger.error(
                    "Reasoning strategy '%s' failed: %s", self._strategies[i].name, result
                )
            else:
                all_findings.extend(result)
        return all_findings


class FinancialReasoningService:
    """Top-level service for the Financial Reasoning Engine."""

    def __init__(self, rag_engine: RAGEngineService, reasoning_engine: ReasoningEngineService):
        """Initialize with RAG and Reasoning engine dependencies."""
        self._rag_engine = rag_engine
        self._reasoning_engine = reasoning_engine

    async def generate_reasoning(self, query: ReasoningQuery) -> ReasoningResult:
        """Full pipeline: Get RAG context, then perform reasoning."""
        rag_context = await self._rag_engine.generate_context(query)
        findings = await self._reasoning_engine.reason(rag_context)
        return ReasoningResult(findings=findings)